grid:
  resolution: 5
  origin_xy: [-85.0, -85.0]
  size_xy: [170, 170]

seed:
  min_points: 3
  use_height_range: true
  use_mean_height: true
  top_k: 5

accept:
  max_height_diff: 0.5
  th_normal: 0.9

debug:
  enable_viz: false
